name: SSD-pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.11.29=py36_0
  - cffi=1.11.5=py36he75722e_1
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.12=h23475e2_2
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1a=h7b6447c_0
  - pcre=8.42=h439df22_0
  - pillow=5.3.0=py36h34e0f95_0
  - pip=18.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - py-opencv=3.4.2=py36hb342d67_1
  - pycparser=2.19=py36_0
  - python=3.6.7=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.6.2=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.25.3=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
  - torchvision=0.2.1=py_2
  - pip:
    - protobuf==3.6.1
    - pyyaml==3.13
    - tensorboardx==1.5
    - torch==1.0.0
    - torch-extension==0.1
    - tqdm==4.28.1
    - yacs==0.1.4
prefix: /home/zhz/anaconda3/envs/SSD-pytorch

